### ISSUE TITLE
chore: validator in taskfile 

### ISSUE THREAD

**Issue by okeypolilla** [okeypolilla/BackupJGT#1]
validar dependencias y pre condiciones 

## Scenario

Validar la instalación de las dependencias necesarias para instalar y configurar correctamente la configuración 

### Acceptance Tests

- validar ansible que este instalado
- validar el paquete apt para la instalación de Ansible  

### Sources:

- [link](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_checkmode.html)

### Examples:

``` yaml 
heck:vars:
    desc: Exist vars for docker
    run: once
    preconditions:
      - sh: test -v CI_REGISTRY_USER
        msg: 'Please add var environment CI_REGISTRY_USER'
      - sh: test -v CI_REGISTRY_PASSWORD
        msg: 'Please add var environment CI_REGISTRY_PASSWORD'
      - sh: test -v CI_REGISTRY
        msg: 'Please add var environment CI_REGISTRY'

```
